project_id = "rbqafiykevtbgztczizr"

[functions.auto-send-signals]
verify_jwt = false

[functions.check-usage]
verify_jwt = false

[functions.telegram-test]
verify_jwt = false

[functions.send-signal-telegram]
verify_jwt = false


[functions.generate-future-signals]
verify_jwt = false

[functions.signal-checker]
verify_jwt = false

