project_id = "rbqafiykevtbgztczizr"

[functions.analyze-chart]
verify_jwt = false

[functions.submit-result]
verify_jwt = false

[functions.check-usage]
verify_jwt = false

[functions.telegram-test]
verify_jwt = false

[functions.send-signal-telegram]
verify_jwt = false
